comment: false
language: R
sudo: false
cache: packages
after_success: - Rscript -e 'covr::codecov()'
codecov:
  token: d4fcb585-8011-4a09-8d47-b4534f1379d5

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true
