comment: false

language: R
sudo: false
cache: packages
after_success: - Rscript -e 'covr::codecov()'
codecov:
  token: 9f49e3ac-688f-4f5d-a23f-aea69ed2b937

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true
